# Generated by Django 5.1.1 on 2024-09-26 09:32

import django.db.models.deletion

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("demo", "0004_articlepage_newsletter_preview"),
        ("wagtail_newsletter", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articlepage",
            name="newsletter_recipients",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="wagtail_newsletter.newsletterrecipients",
            ),
        ),
    ]
